blank_issues_enabled: true
contact_links:
  - name: Questions & Support
    url: https://github.com/REDDE4D/hass-vertical-stacked-navigation-card/discussions
    about: Ask questions and discuss ideas with the community
